[package]
name = "ccommon_rs"
version = "0.1.0"
authors = ["Jonathan Simms <jsimms@twitter.com>"]

[dependencies]

cc_binding = { path = "../cc_binding" }

log = "~0.4"
libc = "~0.2.42"
failure = "~0.1.1"
