[package]
name = "cc_binding"
version = "0.1.0"
authors = ["Jonathan Simms <jsimms@twitter.com>"]

[build-dependencies]
bindgen = "0.37.0"

[lib]
name = "cc_binding"
crate-type = ["rlib", "dylib", "staticlib", "lib"]
